// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cargo.sql

package sqlc

import (
	"context"
)

const createCargo = `-- name: CreateCargo :one
INSERT INTO cargo (
    weight,
    volume,
    type,
    description,
    delivery_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, weight, volume, type, description, delivery_id, created_at, updated_at
`

type CreateCargoParams struct {
	Weight      *float64 `json:"weight"`
	Volume      *float64 `json:"volume"`
	Type        *string  `json:"type"`
	Description *string  `json:"description"`
	DeliveryID  int64    `json:"deliveryId"`
}

func (q *Queries) CreateCargo(ctx context.Context, arg CreateCargoParams) (Cargo, error) {
	row := q.db.QueryRow(ctx, createCargo,
		arg.Weight,
		arg.Volume,
		arg.Type,
		arg.Description,
		arg.DeliveryID,
	)
	var i Cargo
	err := row.Scan(
		&i.ID,
		&i.Weight,
		&i.Volume,
		&i.Type,
		&i.Description,
		&i.DeliveryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCargoByDelivery = `-- name: ListCargoByDelivery :many
SELECT id, weight, volume, type, description, delivery_id, created_at, updated_at FROM cargo
WHERE delivery_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCargoByDeliveryParams struct {
	DeliveryID int64 `json:"deliveryId"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListCargoByDelivery(ctx context.Context, arg ListCargoByDeliveryParams) ([]Cargo, error) {
	rows, err := q.db.Query(ctx, listCargoByDelivery, arg.DeliveryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cargo{}
	for rows.Next() {
		var i Cargo
		if err := rows.Scan(
			&i.ID,
			&i.Weight,
			&i.Volume,
			&i.Type,
			&i.Description,
			&i.DeliveryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
