// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForLinkDeliveriesTransactions implements pgx.CopyFromSource.
type iteratorForLinkDeliveriesTransactions struct {
	rows                 []LinkDeliveriesTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForLinkDeliveriesTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForLinkDeliveriesTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DeliveryID,
		r.rows[0].TransactionID,
	}, nil
}

func (r iteratorForLinkDeliveriesTransactions) Err() error {
	return nil
}

func (q *Queries) LinkDeliveriesTransactions(ctx context.Context, arg []LinkDeliveriesTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"delivery_transaction"}, []string{"delivery_id", "transaction_id"}, &iteratorForLinkDeliveriesTransactions{rows: arg})
}
