// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package sqlc

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customer (
    company_name,
    company_type,
    inn,
    kpp,
    ogrn
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_name, company_type, inn, kpp, ogrn, created_at, updated_at
`

type CreateCustomerParams struct {
	CompanyName string `json:"companyName"`
	CompanyType string `json:"companyType"`
	Inn         string `json:"inn"`
	Kpp         string `json:"kpp"`
	Ogrn        string `json:"ogrn"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CompanyName,
		arg.CompanyType,
		arg.Inn,
		arg.Kpp,
		arg.Ogrn,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Inn,
		&i.Kpp,
		&i.Ogrn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, company_name, company_type, inn, kpp, ogrn, created_at, updated_at FROM customer
ORDER BY created_at
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyType,
			&i.Inn,
			&i.Kpp,
			&i.Ogrn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
