// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_transaction.sql

package sqlc

import (
	"context"
)

type LinkDeliveriesTransactionsParams struct {
	DeliveryID    int64 `json:"deliveryId"`
	TransactionID int64 `json:"transactionId"`
}

const listDeliveriesByTransaction = `-- name: ListDeliveriesByTransaction :many
SELECT d.id, d.pickup_address, d.delivery_address, d.pickup_time, d.delivery_deadline, d.driver_id, d.truck_id, d.customer_id, d.status, d.created_at, d.updated_at FROM delivery_transaction dt
RIGHT JOIN delivery d ON dt.delivery_id = d.id
WHERE dt.transaction_id = $1
`

func (q *Queries) ListDeliveriesByTransaction(ctx context.Context, transactionID int64) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delivery{}
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.PickupAddress,
			&i.DeliveryAddress,
			&i.PickupTime,
			&i.DeliveryDeadline,
			&i.DriverID,
			&i.TruckID,
			&i.CustomerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
