// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: financial_transactions.sql

package sqlc

import (
	"context"
	"time"
)

const createFinancialTransaction = `-- name: CreateFinancialTransaction :one
INSERT INTO financial_transactions (
    amount,
    cargo_id,
    type,
    status,
    transaction_date
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, amount, currency, cargo_id, type, status, transaction_date, created_at, updated_at
`

type CreateFinancialTransactionParams struct {
	Amount          float64   `json:"amount"`
	CargoID         int64     `json:"cargoId"`
	Type            string    `json:"type"`
	Status          string    `json:"status"`
	TransactionDate time.Time `json:"transactionDate"`
}

func (q *Queries) CreateFinancialTransaction(ctx context.Context, arg CreateFinancialTransactionParams) (FinancialTransaction, error) {
	row := q.db.QueryRow(ctx, createFinancialTransaction,
		arg.Amount,
		arg.CargoID,
		arg.Type,
		arg.Status,
		arg.TransactionDate,
	)
	var i FinancialTransaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.CargoID,
		&i.Type,
		&i.Status,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFinancialTransaction = `-- name: UpdateFinancialTransaction :one
UPDATE financial_transactions
SET
    amount = COALESCE($2, amount),
    type = COLESCE($3, type),
    status = COLESCE($4, status),
    transaction_date = COLESCE($5, transaction_date),
    updated_at = now()
WHERE id = $1
RETURNING id, amount, currency, cargo_id, type, status, transaction_date, created_at, updated_at
`

type UpdateFinancialTransactionParams struct {
	ID              int64       `json:"id"`
	Amount          *float64    `json:"amount"`
	Type            interface{} `json:"type"`
	Status          interface{} `json:"status"`
	TransactionDate interface{} `json:"transactionDate"`
}

func (q *Queries) UpdateFinancialTransaction(ctx context.Context, arg UpdateFinancialTransactionParams) (FinancialTransaction, error) {
	row := q.db.QueryRow(ctx, updateFinancialTransaction,
		arg.ID,
		arg.Amount,
		arg.Type,
		arg.Status,
		arg.TransactionDate,
	)
	var i FinancialTransaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.CargoID,
		&i.Type,
		&i.Status,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
