// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Cargo struct {
	ID              int64     `json:"id"`
	AddressSequence []string  `json:"addressSequence"`
	EmployeeID      int64     `json:"employeeId"`
	VehicleID       int64     `json:"vehicleId"`
	StartDate       time.Time `json:"startDate"`
	DeadlineDate    time.Time `json:"deadlineDate"`
	Price           float64   `json:"price"`
	PaymentStatus   int32     `json:"paymentStatus"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
	CustomerID      int64     `json:"customerId"`
}

type Customer struct {
	ID          int64     `json:"id"`
	CompanyName string    `json:"companyName"`
	CompanyType string    `json:"companyType"`
	Inn         string    `json:"inn"`
	Kpp         string    `json:"kpp"`
	Ogrn        string    `json:"ogrn"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Employee struct {
	ID        int64     `json:"id"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type FinancialTransaction struct {
	ID              int64     `json:"id"`
	Amount          float64   `json:"amount"`
	Currency        *string   `json:"currency"`
	CargoID         int64     `json:"cargoId"`
	Type            string    `json:"type"`
	Status          string    `json:"status"`
	TransactionDate time.Time `json:"transactionDate"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
	Description     *string   `json:"description"`
}

type Vehicle struct {
	ID              int64     `json:"id"`
	PlateNumber     string    `json:"plateNumber"`
	Make            *string   `json:"make"`
	Model           *string   `json:"model"`
	Vin             *string   `json:"vin"`
	ManufactureYear *int32    `json:"manufactureYear"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}
