// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Cargo struct {
	ID          int64     `json:"id"`
	Weight      *float64  `json:"weight"`
	Volume      *float64  `json:"volume"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	DeliveryID  int64     `json:"deliveryId"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Customer struct {
	ID          int64     `json:"id"`
	CompanyName string    `json:"companyName"`
	CompanyType string    `json:"companyType"`
	Inn         string    `json:"inn"`
	Kpp         string    `json:"kpp"`
	Ogrn        string    `json:"ogrn"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Delivery struct {
	ID               int64      `json:"id"`
	PickupAddress    string     `json:"pickupAddress"`
	DeliveryAddress  string     `json:"deliveryAddress"`
	PickupTime       *time.Time `json:"pickupTime"`
	DeliveryDeadline time.Time  `json:"deliveryDeadline"`
	DriverID         *int64     `json:"driverId"`
	TruckID          *int64     `json:"truckId"`
	CustomerID       *int64     `json:"customerId"`
	Status           string     `json:"status"`
	CreatedAt        time.Time  `json:"createdAt"`
	UpdatedAt        time.Time  `json:"updatedAt"`
}

type DeliveryTransaction struct {
	DeliveryID    int64 `json:"deliveryId"`
	TransactionID int64 `json:"transactionId"`
}

type Driver struct {
	ID        int64     `json:"id"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Transaction struct {
	ID          int64     `json:"id"`
	Amount      float64   `json:"amount"`
	Currency    string    `json:"currency"`
	Description *string   `json:"description"`
	Category    *string   `json:"category"`
	Type        string    `json:"type"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Truck struct {
	ID          int64     `json:"id"`
	PlateNumber string    `json:"plateNumber"`
	Make        *string   `json:"make"`
	Model       *string   `json:"model"`
	Vin         *string   `json:"vin"`
	Year        *int32    `json:"year"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}
