// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Cargo struct {
	ID              int64          `json:"id"`
	AddressSequence []string       `json:"addressSequence"`
	EmployeeID      int64          `json:"employeeId"`
	VehicleID       int64          `json:"vehicleId"`
	StartDate       time.Time      `json:"startDate"`
	DeadlineDate    time.Time      `json:"deadlineDate"`
	Price           pgtype.Numeric `json:"price"`
	PaymentStatus   int32          `json:"paymentStatus"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       time.Time      `json:"updatedAt"`
}

type Employee struct {
	ID        int64     `json:"id"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Vehicle struct {
	ID              int64     `json:"id"`
	PlateNumber     string    `json:"plateNumber"`
	Make            *string   `json:"make"`
	Model           *string   `json:"model"`
	Vin             *string   `json:"vin"`
	ManufactureYear *int32    `json:"manufactureYear"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}
