// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountDeliveries(ctx context.Context) (int64, error)
	CreateCargo(ctx context.Context, arg CreateCargoParams) (Cargo, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error)
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTruck(ctx context.Context, arg CreateTruckParams) (Truck, error)
	GetDelivery(ctx context.Context, id int64) (Delivery, error)
	GetDriver(ctx context.Context, id int64) (Driver, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetTruck(ctx context.Context, id int64) (Truck, error)
	LinkDeliveriesTransactions(ctx context.Context, arg []LinkDeliveriesTransactionsParams) (int64, error)
	ListCargoByDelivery(ctx context.Context, arg ListCargoByDeliveryParams) ([]Cargo, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]Delivery, error)
	ListDeliveriesByTransaction(ctx context.Context, transactionID int64) ([]Delivery, error)
	ListDeliveriesDetailed(ctx context.Context, arg ListDeliveriesDetailedParams) ([]ListDeliveriesDetailedRow, error)
	ListDrivers(ctx context.Context, arg ListDriversParams) ([]Driver, error)
	ListTrucks(ctx context.Context, arg ListTrucksParams) ([]Truck, error)
	UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (Delivery, error)
	UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
