// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Inserts a new vehicle and returns the created result
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	// Retrieves a single vehicle by ID
	GetVehicle(ctx context.Context, id int64) (Vehicle, error)
	// Retrieves all vehicles ordered by plate number with pagination
	ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]Vehicle, error)
	// Updates a vehicle's information and returns the updated record
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error)
}

var _ Querier = (*Queries)(nil)
