// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package sqlc

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transaction (
    amount,
    currency,
    description,
    category,
    type,
    status
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, amount, currency, description, category, type, status, created_at, updated_at
`

type CreateTransactionParams struct {
	Amount      float64 `json:"amount"`
	Currency    string  `json:"currency"`
	Description *string `json:"description"`
	Category    *string `json:"category"`
	Type        string  `json:"type"`
	Status      string  `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Category,
		arg.Type,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, amount, currency, description, category, type, status, created_at, updated_at FROM transaction
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transaction
SET
    amount = COALESCE($2, amount),
    currency = COALESCE($3, currency),
    description = COALESCE($4, description),
    category = COALESCE($5, category),
    type = COALESCE($6, type),
    status = COALESCE($7, status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, amount, currency, description, category, type, status, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID          int64    `json:"id"`
	Amount      *float64 `json:"amount"`
	Currency    *string  `json:"currency"`
	Description *string  `json:"description"`
	Category    *string  `json:"category"`
	Type        *string  `json:"type"`
	Status      *string  `json:"status"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Category,
		arg.Type,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
