// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: truck.sql

package sqlc

import (
	"context"
)

const createTruck = `-- name: CreateTruck :one
INSERT INTO truck
(plate_number, make, model, vin, year)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, plate_number, make, model, vin, year, created_at, updated_at
`

type CreateTruckParams struct {
	PlateNumber string  `json:"plateNumber"`
	Make        *string `json:"make"`
	Model       *string `json:"model"`
	Vin         *string `json:"vin"`
	Year        *int32  `json:"year"`
}

func (q *Queries) CreateTruck(ctx context.Context, arg CreateTruckParams) (Truck, error) {
	row := q.db.QueryRow(ctx, createTruck,
		arg.PlateNumber,
		arg.Make,
		arg.Model,
		arg.Vin,
		arg.Year,
	)
	var i Truck
	err := row.Scan(
		&i.ID,
		&i.PlateNumber,
		&i.Make,
		&i.Model,
		&i.Vin,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTruck = `-- name: GetTruck :one
SELECT id, plate_number, make, model, vin, year, created_at, updated_at FROM truck
WHERE id = $1
`

func (q *Queries) GetTruck(ctx context.Context, id int64) (Truck, error) {
	row := q.db.QueryRow(ctx, getTruck, id)
	var i Truck
	err := row.Scan(
		&i.ID,
		&i.PlateNumber,
		&i.Make,
		&i.Model,
		&i.Vin,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrucks = `-- name: ListTrucks :many
SELECT id, plate_number, make, model, vin, year, created_at, updated_at FROM truck
ORDER BY plate_number
LIMIT $1 OFFSET $2
`

type ListTrucksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTrucks(ctx context.Context, arg ListTrucksParams) ([]Truck, error) {
	rows, err := q.db.Query(ctx, listTrucks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Truck{}
	for rows.Next() {
		var i Truck
		if err := rows.Scan(
			&i.ID,
			&i.PlateNumber,
			&i.Make,
			&i.Model,
			&i.Vin,
			&i.Year,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
