DROP TABLE IF EXISTS delivery_transaction;
DROP TABLE IF EXISTS transaction;
DROP TABLE IF EXISTS cargo;
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS truck;
DROP TABLE IF EXISTS driver;
